# Generated by Django 5.0.6 on 2024-10-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manage_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_manage_system.courses')),
                ('id_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_manage_system.students')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_manage_system.staffs')),
            ],
        ),
    ]
